Add option to disable rate limiting via AUTH_RATELIMIT=False
Mailu/Mailu pull request #1612
Opened 2020-09-03 23:50 UTC by lub

## What type of PR?

Feature, enhancement

## What does this PR do?

### Related issue(s)
- maybe this conflicts with the changes in #1360, although I think #1360 would need to be rebased anyway

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

2021-01-27 10:27 UTC, nextgens requested changes
The expensive call is nginx.handle_authentication(flask.request.headers) ... this shouldn't run post rate limiting

2021-01-27 10:27 UTC, nextgens commented on core/admin/mailu/internal/views/auth.py
> +    ratelimit = app.config["AUTH_RATELIMIT"]
Rate-limiting after the actual password check is a big no-no, I've proposed an alternative implementation in #1745

2021-06-03 14:30 UTC, Diman0 requested changes
Correct the typo in the doc. I think we can approve the PR after this. 
At a later moment we can look at the changes suggested by Nextgens.

2021-06-03 14:30 UTC, Diman0 commented on docs/configuration.rst
> +Setting this this to ``False`` disables all rate limiting.
You want to remove the duplicate "this" in this sentence.

2021-06-17 16:15 UTC, nextgens commented
IMHO this has very little added value over putting a very high limit. If you want it disabled, set  it to 10000/second or something.

2021-08-06 19:10 UTC, nextgens commented
This has been deprecated by #1910; more work will happen on rate limiting in next releases

2021-08-06 19:10 UTC, closed without merging