Remove startup resolution of HOST_* variables to IP addresses in *_ADDRESS variables
Mailu/Mailu pull request #1716
Opened 2020-12-31 09:54 UTC by tvelocity

## What type of PR?

The *_ADDRESS variables that are initialized at container startup cannot be relied upon, since any IP addresses in them are not guaranteed to remain valid (e.g. when restarting a container). This directly causes issues mentioned in #1341 and is also related with #1430 

The complexity of having two separate addressing mechanisms for Mailu containers is also mentioned in #1133 and #1013 

To avoid any issues with stale addresses, the strategy of resolving host addresses at startup needs to be dropped. Mailu containers can use the HOST_* environment variables directly to reach other containers regardless of their current IP address.

This also means that users with a broken DNS setup, will need to deal with the problem at the source instead of relying on a workaround that makes Mailu unreliable for everyone else.

## What does this PR do?

### Related issue(s)
- Closes #1341 
- Related with #1430 
- Removes complexity mentioned in #1133 and #1013 

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

2020-12-31 12:02 UTC, micw commented
Hello,
I do not exactly understand the purpose of this PR. If you want dynamic address resolution (which absolutely makes sense), just set *_ADDRESS raher than HOST_* - that's it. See the helm chart as an example that actually does this.

2021-01-08 13:55 UTC, tvelocity commented
> Hello,
> I do not exactly understand the purpose of this PR. If you want dynamic address resolution (which absolutely makes sense), just set `*_ADDRESS` raher than `HOST_*` - that's it. See the helm chart as an example that actually does this.

Hello,

Thanks for your feedback. I think it is ok to disagree, however it is not clear to me what the misunderstanding is either. Is there something more specific that is unclear?

The current default behavior directly causes #1341, and I don't seem to be the only one that finds it very very problematic as there are further discussions about this point in #1430 #1133 and #1013. I also don't think that the existence of a workaround makes this any less of an issue, since without it Mailu is broken out of the box.

Docker assumes dynamic addresses for containers, so #1341 likely affects 99% of Mailu setups, and it is only a matter of time and chance until any of them stops working after a restart, reconfiguration or update. This is true for vanilla docker, docker-compose and Kubernetes.

This leaves the user either restarting or recreating his Mailu containers repeatedly until they somehow come up again, or to try to figure out the current behavior, understand the difference between HOST\_ and \_ADDRESS, and finally use \_ADDRESS to override what Mailu does by default.

I think those are valid reasons to remove the startup address resolution. On the other hand, as much as I have tried, I have been unable to find a good reason to keep it. As mentioned in #1341, the startup address resolution should cause issues even in the scenarios that it was supposed to help with (IPv6 DNS lookup bugs in Docker).

**TL; DR:** The \_ADDRESS override's whole purpose is to work around the startup address resolution from HOST\_ to \_ADDRESS. If you are not using it, then you are hit by #1341. If you haven't experienced this issue, you just haven't restarted Mailu enough times yet.

For these reasons, I think it is valid to question whether the startup resolution should even exist in the first place. In my opinion it shouldn't. It adds a layer of complexity, and causes issues without really fixing the issues it was supposed to fix.

2021-01-09 12:48 UTC, micw commented
Hello,

you are right, the HOST_* brings a lot of issues (that's why I added *_ADDRESS and use it in the k8s helm chart). There had been reasons to keep it (but I do not remember what those reasons were and if they still are valid). I'd discuss it in #1013 (which is hopefully the right place) and if the others agree, we can test/merge this.

Kind regards,
Michael.

2021-01-09 12:48 UTC, micw commented
bors try

2021-02-03 16:46 UTC, lub requested changes
Using this PR a couple of days now and the changes seem sensible. As stated in https://github.com/Mailu/Mailu/issues/1341#issuecomment-711086481 I've also bypassed it via the 'old ' `*_ADDRESS` variables and couldn't find any issues with it.

But I've commented on some things regarding the documentation for the changelog(s). 1.8 is already branched off, so further changes should imo be introduced in a separate 1.9 section or omitted for now and added when doing the release.

2021-02-03 16:46 UTC, lub commented on CHANGELOG.md
> +
This change would be in an eventual 1.9, not 1.8. Not sure if it makes sense to clear the entire section when releasing to add new entries like this or alternatively to change it in a single commit when doing the release. Either way currently it's mixed.

2021-02-03 16:46 UTC, lub commented on docs/releases.rst
> +
Kinda similarly to CHANGELOG.md this is in the 1.8 section, although 1.8 already has branched off.

2021-02-03 16:46 UTC, lub commented on towncrier/newsfragments/1341.removal
> +Remove startup resolution of HOST_* variables to *_ADDRESS
Normally the file name points to the PR (#1716), not to the initial issue. That way you can click on it in releases.rst and jump directly to the PR that introduced the described change.

2021-03-25 19:42 UTC, friedrich commented
@tvelocity are you going to address the comments by @lub? It would be great if this could be merged.

2021-06-03 14:59 UTC, Diman0 commented
@tvelocity Are you planning to update this PR?

2021-06-28 21:22 UTC, Diman0 approved these changes
@lub  I have applied your suggestions. I made the newsfragment verbose and added the instructions to it that we should not forget to update changelog.md/releases.rst. Can you review this PR again?

2021-06-29 19:06 UTC, micw commented
I have read through the PR. What bothers me is that this is a breaking change that would instantly make a lot of installations fail as soon as a new image is pulled. That's especially true for installations that use `*_ADDRESS` to already to dynamic host resolution (e.g. helm chart deployments). I think we should have some intermediate solution to support both syntax.

Another thing I saw is that HOST_* variables sometimes contain ports, sometimes not. When we do a breaking change, we should maybe use the chance to sort this out.

And last, I remember that there's one place where we still need host-to-ip resolution. Nginx as mail proxy asks the backend (admin api) for an MTA to proxy to. This _must_ return ip+port and not a hostname, so resolution must be done within admin service. I have not verified wether this is untouched by this PR or not.

2021-06-29 20:05 UTC, Diman0 commented
If this is changed, then it would be a change in a new release. It will not touch existing deployments for people who use mailu 1.7 or 1.8. 
This only has an effect for an upgrade scenario where you are warned of the change in the release notes or a brand new deployment. 

Anyway, this PR does exactly what you want. Only implement dynamic dns resolution. The _ADDRESS workaround is not required anymore. It is now the default behaviour. It also simplifies our installation a lot. We only have one method of name resolution.

The current solution does not work (static IP assignments). Each time when you restart a container it is possible that mailu does not come up (due to ip addresses changing). In such a situation an administrator must manually log on the server and recreate all containers until it finally works again. I have experienced this multiple times already. I rather have dynamic ip resolution that always returns the correct IP address.

>Another thing I saw is that HOST_* variables sometimes contain ports, sometimes not. When we do a breaking change, we should maybe use the chance to sort this out.

What do you mean with this?Can perhaps highlight the line you are referring to?

>And last, I remember that there's one place where we still need host-to-ip resolution. Nginx as mail proxy asks the backend (admin api) for an MTA to proxy to. This must return ip+port and not a hostname, so resolution must be done within admin service. I have not verified wether this is untouched by this PR or not.

Is this situation not covered by the core and filter test? Both send an email to mailu. The tests also connect to read the email. Bors try succeeded. @lub also mentioned that he has run with this PR for multiple days without any issues. @lub can you confirm you also received email when testing the PR and thus can confirm that the nginx mail proxy works?

2021-06-29 20:16 UTC, lub commented
@Diman0 I use this fork on my production system: https://github.com/lub/Mailu/commits/master

So yes, I do receive emails with it. But it needs a rebase before merging iirc.

2021-06-29 20:22 UTC, Diman0 commented
@lub would you be able to rebase it? I do not have a lot of experience with this.

2021-07-14 18:45 UTC, micw commented
In discussion we found another objection. At the moment, hostnames are resolved at system level, so service names and full qualified hostnames are both OK. With the change, we always require full qualified hostnames, especially for the "front" container. We need to investigate here and make it work with service names (because full name is not always known).

2021-11-10 19:16 UTC, Diman0 commented
After the Mailu 1.9 release, we will have a look at implementing this PR. 
We should also have a look at Socrates at the same time. The part that handles DNS resolution in socrates.

2022-10-28 15:36 UTC, Diman0 commented
PR #2460 has been merged which switches Mailu to dynamic DNS resolution. I'm closing this PR.

2022-10-28 15:36 UTC, closed without merging