Doc fixes
Mailu/Mailu pull request #1743
Opened 2021-01-21 23:07 UTC by rbarazzutti

## Documentations fixes

- 82b5920 typos
- 444529b PostgreSQL deprecation (reword)

2021-01-22 00:30 UTC, lub requested changes
Thanks for the fixes, but I think there is a misunderstanding regarding the PostgreSQL image. I hope I could make it clearer :)

2021-01-22 00:30 UTC, lub commented on docs/releases.rst
> +We recommend switching to another database as soon as possible (SQLite or MySQL).
```suggestion
We recommend switching to an external PostgreSQL database as soon as possible.
```

PostgreSQL will be supported in future, just the Mailu PostgreSQL image will be dropped. No need to switch to SQLite or MySQL.

2021-01-22 04:33 UTC, rbarazzutti commented
Thanks for the feedback @lub! Good to learn that PostgreSQL will still have support in the future.

2021-01-22 07:36 UTC, lub approved these changes

2021-01-22 13:21 UTC, Diman0 approved these changes

2021-01-24 17:10 UTC, ofthesun9 commented
bors r+

2021-01-24 18:09 UTC, merged