optimize generation of transport nexthop
Mailu/Mailu pull request #1776
Opened 2021-02-26 20:05 UTC by ghostwheel42

## What type of PR?

bug-fix and enhancement.

## What does this PR do?

Possibly there should be more input validation when editing a relay, but for now this tries to make the best out of the existing "smtp" attribute while maintaining backwards compatibility. When relay is empty, the transport's nexthop is the MX of the relayed domain to fix #1588 

```
RELAY		NEXTHOP
empty		use MX of relay domain => smtp:domain
:port		use MX of relay domain and use port => smtp:domain:port
fqdn		resolve A/AAAA of fqdn => smtp:[fqdn]
fqdn:port	resolve A/AAAA of fqdn and use port => smtp:[fqdn]:port
mx:fqdn		resolve MX of fqdn => smtp:fqdn
mx:fqdn:port	resolve MX of fqdn and use port => smtp:fqdn:port

fqdn can also be an ipv4 address and can optionally be enclosed in [].
an ipv6 address must be enclosed in [].
```

When there is proper input validation and existing database entries are migrated this function can be mad much shorter again.

### Related issue(s)
- closes #1588 

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [X] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/guide.html#changelog) entry file.

2021-06-04 08:55 UTC, Diman0 requested changes
It looks good to me. Can you also update the documentation with the enhanced behaviour and remove the warning about 1588?
I'm referring to  the section relayed domains in [webadministration.rst](https://github.com/Mailu/Mailu/blob/master/docs/webadministration.rst#relayed-domains).

2021-06-16 14:21 UTC, ghostwheel42 commented
> Can you also update the documentation

Hi. I've added some documentation and a new "lmtp:" prefix as discussed via element.

2021-06-16 16:39 UTC, Diman0 commented
Thank you. I will have a look at it later tonight or tomorrow.

2021-06-26 22:50 UTC, Diman0 approved these changes
Sorry for the delay. It looks good to me.

2021-06-27 13:50 UTC, Diman0 commented
@Mergifyio refresh

2021-06-29 10:21 UTC, ghostwheel42 commented
bors try

2021-06-29 10:44 UTC, Diman0 commented
Bors try

2021-06-29 11:59 UTC, Diman0 commented
@Mergifyio refresh

2021-06-29 12:31 UTC, merged