Reflect override settings for postfix
Mailu/Mailu pull request #1806
Opened 2021-05-13 17:00 UTC by ineiti

## What type of PR?

(documentation)

## What does this PR do?

Fixes path in the documentation setting, and also adds how to change postfix.cf

2021-05-18 20:17 UTC, decentral1se approved these changes
LGTM :rocket:

2021-06-04 14:25 UTC, Diman0 requested changes
See the in line comments. The additional tip will be very handy for future users.

2021-06-04 14:25 UTC, Diman0 commented on docs/faq.rst
> +   - ``main.cf`` as ``$ROOT/overrides/postfix.cf``
The actual behaviour is that the overrides reside in $ROOT/overrides/postfix/postfix.cf.
This was changed in mailu 1.8.

2021-06-04 14:25 UTC, Diman0 commented on docs/faq.rst
> +   - ``master.cf`` as ``$ROOT/overrides/postfix.master``
The actual behaviour is that the overrides reside in $ROOT/overrides/postfix/postfix.master.
This was changed in mailu 1.8.

2021-06-07 07:01 UTC, Diman0 approved these changes
Looks good to me. Thank you for your contribution.

2021-06-14 08:45 UTC, ineiti commented
OK, got confused in https://github.com/Mailu/Mailu/pull/1824 because I thought that 1.8 is the new stable. Now that I understand that 1.7 is stable, would it make sense to make a PR against 1.7 with the corrected paths for `postfix.cf` and `master.cf`?

2021-06-16 13:19 UTC, lub approved these changes
lgtm, thank you :)

PRs against previous branches are only opened after changes are merged in master. I don't think we have to backport it to 1.7 in particular, because hopefully 1.8 will be properly released soon.

2021-06-17 07:16 UTC, Diman0 commented
bors retry

2021-06-26 23:21 UTC, Diman0 commented
bors retry

2021-06-26 23:38 UTC, merged