Allow specific users to send email from any address
Mailu/Mailu pull request #1904
Opened 2021-08-02 17:20 UTC by nextgens

## What type of PR?

Feature

## What does this PR do?

Allow specific users to send email from any address using the WILDCARD_SENDERS configuration variable.

### Related issue(s)
- closes #1096

## Prerequistes
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

2021-08-11 15:56 UTC, ghostwheel42 commented
What about making this configurable in the web interface?

2021-08-11 20:51 UTC, nextgens commented
The diff will be a lot larger (db migration, HTML, ...) but sure we can do it. Is it something we want to restrict to admins (ie that only admins can grant?) or something the user can self-elect for (a I-know-what-I'm-doing flag)?

2021-08-14 08:33 UTC, nextgens commented
@ghostwheel42 I am having issues setting up the dev environment properly (see #1577) ... and as such, I am unable to make it configurable through the GUI... currently I rebuild/redeploy the container as required to test my changes and this is way too time intensive for doing something like this...

As users are actively requesting the feature, I propose that we merge it as is and once the instructions on setting up a working dev environment are updated I will endeavour to revisit and implement a GUI for it.

2021-08-18 13:54 UTC, Diman0 commented
That sounds reasonable to me. After this PR is merged, we must not forget to create an issue for adding this GUI config.

2021-08-19 08:28 UTC, ghostwheel42 requested changes
whitespace needs to be remove when using WILDCARD_SENDERS env

2021-08-19 09:09 UTC, Diman0 requested changes
When testing I could only spoof existing email addresses. Is that expected? 
If yes, then please clarify the documentation on this ( I already placed the relevant in-line comment).

The error when using a non-existing email address:
MTP Error (550): Failed to add recipient "user@domain.com" (5.1.0 <doesnotexist@emaildomain.com>: Sender address rejected: User unknown in virtual mailbox table)

2021-08-19 09:09 UTC, Diman0 commented on docs/configuration.rst
> +The ``WILDCARD_SENDERS`` setting is a comma delimited list of user email addresses that are allowed to send emails from any address (spoofing the sender).
Could you clarify this further that you can only spoof existing email addresses? For example:

The ``WILDCARD_SENDERS`` setting is a comma delimited list of user email addresses that are allowed to send emails from any existing email address (spoofing the sender).

2021-08-19 09:11 UTC, nextgens commented on core/admin/mailu/internal/views/postfix.py
> +    wildcard_senders = flask.current_app.config["WILDCARD_SENDERS"].lower().split(',') if has_wildcard_senders else []
Good idea; done in 7252a73e118650fc0737e9df39e07c853af53ac0

2021-08-19 09:27 UTC, nextgens commented
bors try

2021-08-19 10:36 UTC, nextgens commented
bors ping

@mergifyio ping

2021-08-19 10:36 UTC, nextgens commented
bors cancel
bors retry

2021-08-19 10:37 UTC, nextgens commented
bors retry

2021-08-19 11:08 UTC, Diman0 commented
another attempt

bors try

2021-08-19 11:09 UTC, Diman0 commented
bors cancel

2021-08-19 11:09 UTC, Diman0 commented
bors try

2021-08-19 11:14 UTC, Diman0 commented
bors retry

2021-08-19 11:16 UTC, Diman0 commented
Hmm I see that BORS crashed (https://app.bors.tech/repositories/6693/log). 
I will built the images locally and test with whitespace in the variable.  After that I will approve and check if the bors r+ from mergify is picked up. If it still fails, I can always merge it manually.

2021-08-19 12:19 UTC, Diman0 submitted a review, later dismissed
With the latest changes I cannot send any emails anymore. It does not matter if the env var WILDCARD_SENDERDS is set or is not set (commented). Sending any email results in the error:

SMTP Error (451): Failed to add recipient "recipient@recipient_domain.nl" (4.3.0 <sender@sender_domain.nl>: Temporary lookup failure).

Can you double check on your environment if you experience the same?

2021-08-19 12:55 UTC, nextgens commented
It looks like I've screwed up the merge... I hate git.

2021-08-19 13:22 UTC, nextgens commented
bors try

2021-08-19 13:22 UTC, nextgens commented
@Diman0 give it another shot please, this works for me now

2021-08-19 13:45 UTC, nextgens commented
bors try

2021-08-19 13:45 UTC, nextgens commented
bors cancel

2021-08-19 14:23 UTC, Diman0 commented
bors is working again. I will review it this evening.

2021-08-19 14:47 UTC, Diman0 approved these changes
Looking good now. The test with wildcard variable with lots of spaces succeeded now.

2021-08-19 15:08 UTC, merged

2021-09-24 12:32 UTC, miroslavskela commented
Hello,
I have problem with this setting. Have implemented everything in  /mailu/data/overrides, and also after that didn't work moved to /mailu/overrides, but still cant sent mail even as another user on same mail server, with same domain.Does anyone have some idea what could be problem. sender_logins and sasl_passwd are empty. Thank you!