Add input validation for domain creation
Mailu/Mailu pull request #2210
Opened 2022-02-01 12:09 UTC by 0pc0deFR

## What type of PR?

bug-fix

## What does this PR do?

This patch add the input validation for domain creation.

### Related issue(s)
- Mention an issue like: #1817
- Auto close an issue like: closes #1817

2022-02-03 12:42 UTC, Diman0 submitted a review, later dismissed
Interesting. I did not notice before we were using the validators library which is documented here
https://validators.readthedocs.io/en/latest/index.html#module-validators.domain
It also contains other interesting validators we could use in more locations in the Mailu web admin.

Can you add a changelog entry? It is documented here:
https://mailu.io/1.9/contributors/workflow.html#changelog

2022-02-04 14:13 UTC, 0pc0deFR commented
@Diman0 It's done.

2022-02-13 16:26 UTC, nextgens requested changes

2022-02-13 16:26 UTC, nextgens commented on core/admin/mailu/ui/views/domains.py
> +        if validators.domain(form.name.data) is True:
Please use ``if validators.domain(form.name.data):`` instead

2022-02-17 12:49 UTC, Diman0 commented
bors try

2022-02-17 13:08 UTC, Diman0 commented
bors try-

```
admin_1      |   File "/app/mailu/ui/views/domains.py", line 21, in domain_create
admin_1      |     if validators.domain(form.name.data):
admin_1      | NameError: name 'validators' is not defined
```

Did you test your code? It misses the import for the validators library.
You also changed the behavior that in an error situation you are returned to the domain list page. Everything you entered on the domain create page is gone now. 

I will address this and push a commit.

2022-02-17 13:11 UTC, Diman0 commented
bors try

After bors try succeeds I will approve the PR.

2022-02-17 16:40 UTC, Diman0 approved these changes
lgtm

2022-03-12 12:33 UTC, ghostwheel42 approved these changes

2022-03-12 12:54 UTC, merged