Configurable default spam threshold used for new users
Mailu/Mailu pull request #2328
Opened 2022-04-26 20:07 UTC by enginefeeder101

## What type of PR?

Feature

## What does this PR do?

This PR adds functionality to set a custom default spam threshold
for new users. The environment variable ``DEFAULT_SPAM_THRESHOLD`` is
be used for this purpose. When not set, it defaults back to 80%, as the
default value was before.

If ``DEFAULT_SPAM_THRESHOLD`` is set to a value that Python cannot
parse as an integer, a ValueError is thrown. There is no error handling
for that case built-in. Should that be done?

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

2022-06-08 07:53 UTC, Diman0 requested changes
Thank you for submitting this PR. This PR is worthwhile. I can imagine that administrators want the possibility for setting a default threshold. But the PR requires some changes. We normally assign all environment variables to a global dictionary (app.config). This dictionary is used in other parts of Mailu.

So don't use the env var directly in models.py. Add the value to the global config.
In [configuration.py](https://github.com/Mailu/Mailu/blob/master/core/admin/mailu/configuration.py) add DEFAULT_SPAM_THRESHOLD to the default config (line 7+):
`'DEFAULT_SPAM_THRESHOLD': 80,`

In Class ConfigManager, in function init_app (see line 136+), you can add the code for assigning the value to the config:
`self.config['DEFAULT_SPAM_THRESHOLD'] = int(self.config['DEFAULT_SPAM_THRESHOLD'])`
This would be the ideal location to add error handling. It is not required. We don't have error handling for any of the other mailu.env environment variables.

Finally in models.py on line 511 you can use now:
`spam_threshold = db.Column(db.Integer, nullable=False,
        default=int(app.config['DEFAULT_SPAM_THRESHOLD]))`

The documentation changes looks fine.

2022-07-04 14:47 UTC, Diman0 commented
At a glance it looks good to me. I will test and review the PR this week.

bors try

2022-07-04 15:19 UTC, Diman0 commented
bors retry

2022-07-05 11:11 UTC, Diman0 requested changes
See in-line comment

2022-07-05 11:11 UTC, Diman0 commented on docs/antispam.rst
> +   The default spam filter tolerance used for new users can be configured using the environment variable ``DEFAULT_SPAM_THRESHOLD``. See also: :ref:`_advanced_cfg`.
The build fails with the following error for the documentation:
`/docs/antispam.rst:46:undefined label: _advanced_cfg`

When referring to a bookmark you should not include the leading _ of the bookmark. 
Try changing ```:ref:`_advanced_cfg`.``` to ```:ref:`advanced_cfg` ```.

In the future I also recommend to try building and testing the images manually before submitting a PR or pushing commits to a PR. How to is described here:
https://mailu.io/1.9/contributors/environment.html#building-images
This way you can see beforehand that the build fails..

2022-07-06 14:32 UTC, Diman0 submitted a review, later dismissed
See in-line comment

2022-08-19 18:02 UTC, Diman0 commented
Everything should be fixed. Let's run the test suite

bors try

2022-08-19 18:21 UTC, Diman0 commented
bors try

2022-08-19 18:25 UTC, Diman0 commented
bors retry

2022-08-19 19:25 UTC, Diman0 commented
bors retry

2022-08-19 20:25 UTC, Diman0 submitted a review, later dismissed
lgtm

2022-10-29 09:12 UTC, Diman0 commented
bors try

2022-10-29 10:24 UTC, Diman0 approved these changes
lgtm. I tested the functionality works as expected

2022-10-29 11:43 UTC, ghostwheel42 approved these changes
Lgtm

2022-10-29 11:51 UTC, merged