Upgrade Snappymail to 2.21 and merge the webmail containers
Mailu/Mailu pull request #2526
Opened 2022-11-12 10:37 UTC by nextgens

## What type of PR?

enhancement

## What does this PR do?

Upgrade Snappymail to 2.21 and merge the webmail containers. This will make the CI faster and should simplify things going forward.

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [ ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

2022-11-12 10:47 UTC, nextgens commented
bors try

2022-11-12 10:51 UTC, nextgens commented
bors try

2022-11-12 10:54 UTC, nextgens commented
bors retry

2022-11-12 13:28 UTC, nextgens commented
bors try

2022-11-12 13:35 UTC, nextgens commented
bors retry

2022-11-12 13:36 UTC, nextgens commented
bors retry

2022-11-12 13:50 UTC, nextgens commented
bors try

2022-11-12 14:12 UTC, nextgens commented
bors try

2022-11-12 14:21 UTC, nextgens commented
bors retry

2022-11-12 14:28 UTC, nextgens commented
bors try

2022-11-12 14:39 UTC, nextgens commented
bors try

2022-11-12 15:07 UTC, nextgens commented
bors try

2022-11-12 15:12 UTC, nextgens commented
bors try

2022-11-12 15:21 UTC, nextgens commented
bors try

2022-11-13 13:42 UTC, nextgens commented
bors try

2022-11-13 14:26 UTC, nextgens commented
bors try

2022-11-21 13:41 UTC, Diman0 commented
bors try

2022-11-21 13:46 UTC, Diman0 requested changes
See in-line comment.

All changes look fine to me. I still have to test it, before I approve it.

2022-11-21 13:55 UTC, nextgens commented on webmails/Dockerfile
> +COPY php-webmail.conf /etc/php81/php-fpm.d/php-webmail.conf
done in 28d720bb

2022-11-21 13:55 UTC, Diman0 commented
bors try

2022-11-21 15:05 UTC, nextgens commented
bors try

2022-11-21 15:06 UTC, Diman0 commented
bors try

2022-11-21 15:22 UTC, Diman0 approved these changes
LGTM

2022-11-21 15:36 UTC, merged