Restful api finishing touches
Mailu/Mailu pull request #2631
Opened 2023-01-25 16:20 UTC by Diman0

## What type of PR?

enhancement

## What does this PR do?
Some finishing touches for the restful api.

- Make the API configurable via the setup utility.  
  - Configured exactly the same as the ADMIN and WEBMAIL. 
- We have a single config (API) that configures whether it is exposed (via front). Just like ADMIN. The API is always reachable by directly connecting to the admin container.
- API_TOKEN does not enable/disable the API anymore. When it is not configured, an error is returned (via the internet browser) that the API_TOKEN must be configured in mailu.env.
- Fix some small bugs in the setup utility ( selecting none in the dropdown boxes, now correctly changes the config)
- Update Flask-RestX to 1.0.5. This resolves the deprecation warnings introduced by Flask-RestX.

### Related issue(s)

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

2023-01-25 19:15 UTC, ghostwheel42 commented
bors try

2023-01-25 19:25 UTC, ghostwheel42 commented
bors try

2023-01-25 19:25 UTC, ghostwheel42 commented on core/admin/mailu/api/__init__.py
> +        app.register_blueprint(APIv1.blueprint, url_prefix=f'{web_api_root}/v{int(APIv1.VERSION)}')
Using `int()` is not necessary in a format string

2023-01-25 20:14 UTC, ghostwheel42 commented
bors try

2023-01-26 17:30 UTC, ghostwheel42 requested changes
When testing API was enabled by default in the setup container.
I think it should be disabled.

2023-01-26 17:32 UTC, ghostwheel42 commented
ah, and I think there should be a small example hex token in the API_TOKEN text field
Otherwise this LGTM

2023-01-27 13:20 UTC, Diman0 commented
@ghostwheel42 
I have made the proposed changes. For generating the token I simply picked the first JavaScript sample I could find for generating passwords. A static token felt too insecure for me. We don't want 50% of all Mailu installations to use the same token.

2023-01-27 18:46 UTC, ghostwheel42 approved these changes
LGTM

2023-01-27 18:56 UTC, merged