Update to docker compose v2
Mailu/Mailu pull request #2665
Opened 2023-02-15 09:30 UTC by nextgens

## What type of PR?

documentation

## What does this PR do?

Update to docker compose v2

### Related issue(s)
- close #2663

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x] In case of feature or enhancement: documentation updated accordingly
- [ ] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

2023-02-20 10:42 UTC, ghostwheel42 requested changes

2023-02-20 10:42 UTC, ghostwheel42 commented on docs/cli.rst
> +  $ docker compose exec admin flask mailu config-export user.spam_threshold
```suggestion
  $ docker compose exec -T admin flask mailu config-export user.email user.spam_threshold
```

2023-02-20 10:42 UTC, ghostwheel42 commented on docs/cli.rst
> +  $ docker compose exec admin flask mailu config-export --help
```suggestion
  $ docker compose exec -T admin flask mailu config-export --help
```

2023-02-20 10:42 UTC, ghostwheel42 commented on docs/cli.rst
> +  $ docker compose exec admin flask mailu config-export domain.dns_mx domain.dns_spf
```suggestion
  $ docker compose exec -T admin flask mailu config-export domain.dns_mx domain.dns_spf
```

2023-02-20 10:42 UTC, ghostwheel42 commented on docs/cli.rst
> +  docker exec -i $(docker compose ps -q admin) flask mailu config-import -nv < mail-config.yml
```suggestion
  docker compose exec -T admin flask mailu config-import -nv < mail-config.yml
```

2023-02-20 10:42 UTC, ghostwheel42 commented on tests/compose/test.py
> +print(subprocess.check_output("docker compose -f " + compose_file + " up -d", shell=True).decode())
I think we should start using f-strings here. 

```suggestion
print(subprocess.check_output(f"docker compose -f {compose_file} up -d", shell=True).decode())
```

2023-02-20 10:42 UTC, ghostwheel42 commented on tests/compose/test.py
> +    print(subprocess.check_output("docker compose -f " + compose_file + " down", shell=True).decode())
I think we should start using f-strings here. 

```suggestion
    print(subprocess.check_output(f"docker compose -f {compose_file} down", shell=True).decode())
```

2023-02-20 11:11 UTC, ghostwheel42 commented
bors try

2023-03-11 10:34 UTC, Diman0 commented
bors try

2023-03-11 10:49 UTC, Diman0 commented
Twice the same error on the webmail test. Apparently something is different with docker compose v2 that breaks the test.
```
Running hooks
Error: No such object: webmail_webmail_1
The default page of snappymail hasn't returned 200 but 000!
Error: [ERROR]: output = , error code = 1
Printing logs ...
```

2023-03-11 11:00 UTC, nextgens commented
bors try

2023-03-11 13:27 UTC, Diman0 requested changes
Found it. In docker compose V2 underscores have changed to hypens in the names. A pretty big breaking change if you ask me.

https://github.com/Mailu/Mailu/blob/0de2430868853fa7a3a6edc8d8175cb786b37d23/tests/compose/webmail/01_ensure_admin_unreachable.sh#L3
Change `webmail_webmail_1` to `webmail-webmail-1` and the test should now work fine.

2023-03-11 13:28 UTC, nextgens commented
@Diman0 yeah, I've fixed it already :)

2023-03-11 13:28 UTC, Diman0 commented
Nvm. I did not see the PR was updated with this change.

2023-03-11 13:33 UTC, Diman0 approved these changes
LGTM

2023-03-11 13:41 UTC, merged