Build multi-arch images, retry mechanism for builds, improved releases
Mailu/Mailu pull request #2712
Opened 2023-03-21 14:54 UTC by Diman0

## What type of PR?

feature

## What does this PR do?
Switch to building multi-arch images. The images build for pull requests, master and production are now multi-arch images for the architectures:
* linux/amd64
* linux/arm64/v8
* linux/arm/v7

Enhance CI/CD workflow with retry functionality. All steps for building images are now automatically retried. If a build temporarily fails due to a network error, the retried step will still succeed.

Provide a changelog for minor releases. The github release will now:
* Provide the changelog message from the newsfragment of the PR that triggered the backport.
* Provide a github link to the PR/issue of the PR that was backported.

### Related issue(s)
- #1582
- #1200
- #2215
- closes #2653

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [x ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

2023-03-21 14:58 UTC, Diman0 commented
Currently the tests are not run for the arm images. Should this also be implemented? 
It does mean that the workflow will take a bit longer. However, it does mean we catch any arm-specific issues which prevent the images from starting normally.

2023-03-21 22:34 UTC, Diman0 commented
bors try

2023-03-23 12:13 UTC, Diman0 commented
bors try

2023-03-23 12:38 UTC, nextgens commented on docs/compose/requirements.rst
> +system agnostic as long as a fairly recent Linux kernel is running and
on windows or elsewhere the linux kernel will be emulated

2023-03-23 14:10 UTC, Diman0 commented on docs/compose/requirements.rst
>  the Docker API (>= 1.11) is available.
I'm fine with removing this.

2023-03-23 14:45 UTC, nextgens commented on docs/compose/requirements.rst
> +system agnostic as long as a fairly recent Linux kernel is running and
It should be all transparent ; see https://docs.docker.com/desktop/windows/wsl/

Not something we need to be explicit about IMHO

2023-03-23 14:47 UTC, nextgens requested changes

2023-03-23 14:47 UTC, nextgens commented on docs/setup.rst
> +You are free to choose any linux operating system that runs Docker (>= 1.11),
```suggestion
```

2023-03-23 14:49 UTC, nextgens submitted a review, later dismissed

2023-03-23 15:19 UTC, merged