Hardened malloc was not disabled for oletools when an CPU with missing flags is used
Mailu/Mailu pull request #2961
Opened 2023-10-06 09:53 UTC by Diman0

## What type of PR?
bug fix

## What does this PR do?
Updates oletools to also disable hardened malloc when used CPU misses flags

### Related issue(s)
- closes #2959 

## Prerequisites
Before we can consider review and merge, please make sure the following list is done and checked.
If an entry in not applicable, you can check it or remove it from the list.

- [n/a ] In case of feature or enhancement: documentation updated accordingly
- [x] Unless it's docs or a minor change: add [changelog](https://mailu.io/master/contributors/workflow.html#changelog) entry file.

2023-10-06 09:54 UTC, Diman0 commented
I will set the WIP flag until I have replicated the issue locally and confirmed this PR resolves it.

2023-10-06 09:58 UTC, nextgens commented
[x86_64.txt](https://github.com/Mailu/Mailu/files/12829585/x86_64.txt)
[arm64.txt](https://github.com/Mailu/Mailu/files/12829586/arm64.txt)

Here are the instructions in use... so we need 'avx2' for vpunpckldq, what else?

2023-10-06 10:52 UTC, nextgens requested changes

2023-10-06 10:52 UTC, nextgens commented on core/base/libs/socrate/socrate/system.py
> +            if line.startswith('flags') and ' avx ' not in line and ' avx2 ' not in line:
```suggestion
            if line.startswith('flags') and ' avx2 ' not in line:
```
You won't find a CPU that does the later but not the former.

As currently spelt out, if either is present the test will skip. This is not what we want, we want both to be present.

2023-10-06 10:52 UTC, nextgens commented on core/base/libs/socrate/socrate/system.py
> +            if line.startswith('flags') and ' avx ' not in line and ' avx2 ' not in line:
We may want to explain in the warning line 83 that we are missing vectorized instructions

2023-10-06 12:07 UTC, nextgens submitted a review, later dismissed
LGTM

2023-10-06 14:33 UTC, Diman0 commented
Please reject the PR. It does not work yet.
I think I figured out the problem.
In the Dockerfile of the base image we enable the hardened malloc:
https://github.com/Mailu/Mailu/blob/dd1de62eb0e3e0f7a6dec1de5c57c3b64bb54d9b/core/base/Dockerfile#L82

As a result, the test in system.py to enable/disable hardened malloc cannot be even reached. Start.py is already run with the hardened malloc due to LD_PRELOAD=LD_PRELOAD="/usr/lib/libhardened_malloc.so being set. So incompatible systems will have the problem that start.py immediately crashes.

I propose to 
1. set `LD_PRELOAD=` in the base image. 
2. Adapt the hardened malloc test in system.py to enable the hardened malloc via LD_PRELOAD= if requirements are met (cpu flags/features  are present)

2023-10-07 08:04 UTC, nextgens commented
bors try

2023-10-07 08:09 UTC, nextgens commented
bors try

2023-10-07 08:25 UTC, nextgens commented
bors try

2023-10-07 08:55 UTC, nextgens commented
bors try

2023-10-07 11:45 UTC, nextgens commented
@Diman0 are we happy with this now?

We may want to double check that it works in practice: use lsof to see if all PIDs of all containers are using the library

2023-10-08 07:50 UTC, Dennis14e commented
Just my 2 cents: Wouldn't it be nicer to have a custom environment variable like "ENABLE_HARDENED_MALLOC" instead of the user setting LD_PRELOAD themselves?
Maybe LD_PRELOAD is needed for something else too at some point or an Alpine update changes the path or something similar.

Greetings & thanks for Mailu!

2023-10-08 09:58 UTC, Diman0 commented
> Just my 2 cents: Wouldn't it be nicer to have a custom environment variable like "ENABLE_HARDENED_MALLOC" instead of the user setting LD_PRELOAD themselves? Maybe LD_PRELOAD is needed for something else too at some point or an Alpine update changes the path or something similar.
> 
> Greetings & thanks for Mailu!

The point is that hardened malloc can only be made available for the entrypoint process if LD_PRELOAD is already set when the container is started. 

@nextgens It looks good to me. I will double check that it runs as expected on the VM with an outdated cpu (qemu64) and on a VM with a modern cpu with hardened malloc enabled.

2023-10-08 10:06 UTC, Diman0 commented
@nextgens It looks good to me.
On an outdated CPU (e.g. with CPU type qemu64), I do not see the warnings in the logs and Mailu starts fine.
On a modern CPU, I do get the warning to enable hardened malloc.
When running with LD_PRELOAD (hardened malloc enabled), the output of lsof confirms this.

2023-10-08 10:34 UTC, nextgens approved these changes

2023-10-08 11:59 UTC, Diman0 commented
bors retry

2023-10-08 12:09 UTC, Diman0 commented
bors retry

2023-10-08 12:11 UTC, nextgens commented
bors retry

2023-10-08 12:17 UTC, nextgens commented
bors try

2023-10-08 12:29 UTC, nextgens commented
bors r+

2023-10-08 12:59 UTC, nextgens approved these changes

2023-10-08 13:01 UTC, nextgens commented
bors r+

2023-10-08 13:14 UTC, Diman0 commented
bors r+

2023-10-08 13:38 UTC, nextgens commented
@mergifyio backport

2023-10-08 13:41 UTC, merged